plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
}

android {
    namespace 'io.imito.woundgenius.sample'
    compileSdk 36

    defaultConfig {
        minSdk 26
        targetSdk 36
        versionCode 228
        versionName "1.5.0.16"
        applicationId "io.imito.woundgenius.sample"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    // Define flavor dimensions (groups)
    flavorDimensions "environment", "cpu"

    productFlavors {
        production {
            dimension "environment"
        }
        internal {
            dimension "environment"
        }
        universal {
            dimension "cpu"
            ndk {
                abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
            }
        }
        x86_64 {
            dimension "cpu"
            ndk {
                abiFilters 'x86_64'
            }
        }
        x86 {
            dimension "cpu"
            ndk {
                abiFilters 'x86'
            }
        }
        armeabi_v7a {
            dimension "cpu"
            ndk {
                abiFilters 'armeabi-v7a'
            }
        }
        arm64_v8a {
            dimension "cpu"
            ndk {
                abiFilters 'arm64-v8a'
            }
        }
    }
    packagingOptions {
        exclude 'lib/**/lib*.so'
        pickFirst 'lib/x86_64/lib*.so' // Include only x86_64 for x86_64 flavor
        pickFirst 'lib/x86/lib*.so'    // Include only x86 for x86 flavor
        pickFirst 'lib/armeabi-v7a/lib*.so'// Include only armeabi-v7a for armeabi-v7a flavor
        pickFirst 'lib/arm64-v8a/lib*.so'   // Include only arm64-v8a for arm64-v8a flavor
    }


    applicationVariants.all { variant ->
        def projectName = rootProject.name
        def versionName = variant.versionName
        def versionCode = variant.versionCode
        variant.outputs.all {
            outputFileName = "${projectName}-v${versionName}(${versionCode}).apk"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
    buildFeatures {
        viewBinding true
    }
    ndkVersion '27.0.11902834'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    api "io.imito.woundgenius:sdk:1.5.0"

    // uncomment when working with sdk module

    implementation platform('com.google.firebase:firebase-bom:34.2.0')
    implementation("com.google.firebase:firebase-analytics")

    //dagger
    ksp 'com.google.dagger:dagger-compiler:2.57.1'
    ksp 'com.google.dagger:dagger-android-processor:2.57.1'
    implementation 'com.google.dagger:dagger:2.57.1'
    implementation 'com.google.dagger:dagger-android:2.57.1'
    implementation 'com.google.dagger:dagger-android-support:2.57.1'

    //multidex
    implementation 'androidx.multidex:multidex:2.0.1'

    //rx
    implementation "io.reactivex.rxjava2:rxjava:2.2.21"
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation("io.reactivex.rxjava2:rxkotlin:2.4.0")

    //MPAndroidChart
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    ksp ("androidx.room:room-compiler:2.8.0")
    implementation ("androidx.room:room-ktx:2.8.0")
    api ("androidx.room:room-runtime:2.8.0")
    androidTestImplementation 'androidx.room:room-testing:2.8.0'
    implementation 'androidx.room:room-rxjava2:2.8.0'

    //swipe to delete recycler
    implementation 'com.github.rambler-digital-solutions:swipe-layout-android:1.0.17'

    // lifecycle
    implementation "androidx.lifecycle:lifecycle-common-java8:2.9.3"
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation "androidx.lifecycle:lifecycle-common-java8:2.9.3"
    androidTestImplementation 'androidx.arch.core:core-testing:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.3'

    implementation 'com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0'

    //glide
    implementation 'com.github.bumptech.glide:glide:5.0.4'
    ksp 'com.github.bumptech.glide:compiler:5.0.4'

    //timber
    implementation 'com.jakewharton.timber:timber:5.0.1'

    //hawk
    implementation "com.orhanobut:hawk:2.0.1"

    //retrofit
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'

    //exoplayer
    implementation("androidx.media3:media3-exoplayer:1.8.0")
    implementation("androidx.media3:media3-ui:1.8.0")
}