plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    namespace 'com.example.samplewoundsdk'
    compileSdk 34

    defaultConfig {
        minSdk 26
        targetSdk 34
        versionCode 180
        versionName "1.3.1.9"
        applicationId "com.example.samplewoundsdk"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    // Define flavor dimensions (groups)
    flavorDimensions = ["cpu"]

    productFlavors {
        universal {
            dimension "cpu"
            ndk {
                abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
            }
        }
        x86_64 {
            dimension "cpu"
            ndk {
                abiFilters 'x86_64'
            }
        }
        x86 {
            dimension "cpu"
            ndk {
                abiFilters 'x86'
            }
        }
        armeabi_v7a {
            dimension "cpu"
            ndk {
                abiFilters 'armeabi-v7a'
            }
        }
        arm64_v8a {
            dimension "cpu"
            ndk {
                abiFilters 'arm64-v8a'
            }
        }
    }

    packagingOptions {
        exclude 'lib/**/lib*.so'
        pickFirst 'lib/x86_64/lib*.so' // Include only x86_64 for x86_64 flavor
        pickFirst 'lib/x86/lib*.so'    // Include only x86 for x86 flavor
        pickFirst 'lib/armeabi-v7a/lib*.so'// Include only armeabi-v7a for armeabi-v7a flavor
        pickFirst 'lib/arm64-v8a/lib*.so'   // Include only arm64-v8a for arm64-v8a flavor
    }

    applicationVariants.all { variant ->
        def projectName = rootProject.name
        def versionName = variant.versionName
        def versionCode = variant.versionCode
        variant.outputs.all {
            outputFileName = "${projectName}-v${versionName}(${versionCode}).apk"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/atomicfu.kotlin_module'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
    buildFeatures {
        viewBinding true
    }
    ndkVersion '25.1.8937393'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'


    implementation 'com.example.woundsdk:woundgeniussdk:1.3.5'

    implementation platform('com.google.firebase:firebase-bom:31.2.2')
    implementation 'com.google.firebase:firebase-analytics-ktx'

    //dagger
    kapt 'com.google.dagger:dagger-compiler:2.51.1'
    kapt 'com.google.dagger:dagger-android-processor:2.48'
    implementation 'com.google.dagger:dagger:2.51.1'
    implementation 'com.google.dagger:dagger-android:2.48'
    implementation 'com.google.dagger:dagger-android-support:2.48'

    //multidex
    implementation 'androidx.multidex:multidex:2.0.1'

    //rx
    implementation "io.reactivex.rxjava2:rxjava:2.2.21"
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation("io.reactivex.rxjava2:rxkotlin:2.4.0")

    //MPAndroidChart
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    // Room components
    implementation "androidx.room:room-runtime:2.6.1"
    implementation "androidx.room:room-ktx:2.6.1"
    kapt "androidx.room:room-compiler:2.6.1"
    androidTestImplementation 'androidx.room:room-testing:2.6.1'
    implementation 'androidx.room:room-rxjava2:2.6.1'

    //swipe to delete recycler
    implementation 'com.github.rambler-digital-solutions:swipe-layout-android:1.0.17'

    // lifecycle
    implementation "androidx.lifecycle:lifecycle-common-java8:2.8.7"
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation "androidx.lifecycle:lifecycle-common-java8:2.8.7"
    androidTestImplementation 'androidx.arch.core:core-testing:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'

    implementation 'com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0'

    //glide
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    kapt 'com.github.bumptech.glide:compiler:4.16.0'

    //timber
    implementation 'com.jakewharton.timber:timber:5.0.1'

    //hawk
    implementation "com.orhanobut:hawk:2.0.1"

    //retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'

    //exoplayer
    implementation("androidx.media3:media3-exoplayer:1.4.0")
    implementation("androidx.media3:media3-ui:1.4.0")
}