// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
        maven { url 'https://jitpack.io' }
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
        classpath 'com.google.gms:google-services:4.4.3'
        classpath "com.klaxit.hiddensecrets:HiddenSecretsPlugin:0.2.1"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.1.0-1.0.29"
        classpath "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:2.1.0"
        classpath "org.sonarqube:org.sonarqube.gradle.plugin:7.3.1.8318"
    }
}


allprojects {
    repositories {
        repositories {
            maven { url "SDK" }
        }
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.zohodl.com/' }
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}